### PR TITLE
Update Core.py

### PR DESCRIPTION
**Pull request by RDIL**

### CODE REVIEW

**Review by rocketpropelledpotato — DISMISSED** [review]
Let’s try to limit the profanity to 0 words.

**Comment by RDIL** [comment]
Nah fam

**Comment by RDIL** [comment]
Boy

**Comment by RDIL** [comment]
You do realize that since I’m a collaborator I can still talk here right?

**Review by RDIL — COMMENTED** [review]
I fixed it 🥇

**Comment by RDIL** [comment]
@rocketpropelledpotato reviewewwwwwwwe

**Comment by RDIL** [comment]
Oh well

**Pull request merged**
